"""initial models

Revision ID: 0b0e190d286c
Revises: 
Create Date: 2025-10-26 13:58:50.934674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0e190d286c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if admin_user table exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'admin_user' not in tables:
        op.create_table('admin_user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_admin', sa.String(length=120), nullable=False),
            sa.Column('password_admin', sa.String(length=255), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_admin', name='uq_admin_user_username')
        )

    if 'curso' in tables:
        # Add unique constraint to curso.nome if table exists
        op.create_unique_constraint("uq_curso_nome", "curso", ["nome"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if constraints/tables exist before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'curso' in tables:
        op.drop_constraint("uq_curso_nome", "curso", type_="unique")
    
    if 'admin_user' in tables:
        op.drop_table('admin_user')
    # ### end Alembic commands ###
